<?php

function renderElement($element) {
    $arrowHtml = count($element['children']) > 0 ? '<div class="arrow">❯</div>' : '';
    $html = '<div class="tree" data-id="' . $element['id'] . '">
                <div class="title">' . $arrowHtml . $element['name'] . ' <div class="delete"><img src="/img/delete.png"></div></div>
                <div class="children"><div>';

    foreach ($element['children'] as $child) {
        $html .= renderElement($child);
    }

    $html .= '</div></div>
</div>';

    return $html;
}

?>

<div class="preloader">
    <div></div>
</div>


<button class="btn btn-primary" id="generate" type="button">Сгенерировать</button>
<div class="mt-2">
    <input class="form-control" id="search" placeholder="Поиск">
</div>
<div id="tree_list" class="mt-3">
    <?php
    foreach ($this->elements as $element) {
        echo renderElement($element);
    }
    ?>

</div>

<script src="https://cdn.jsdelivr.net/npm/@shopify/draggable@1.0.0-beta.11/lib/draggable.bundle.js"></script>
<script type="module" src="/js/index.js"></script>