<div>
    <input class="form-control" id="search">
</div>
<div id="tree_list">
    <div class="tree">
        <div class="title">Title</div>
        <div class="children">

            <div>

                <div class="tree">
                    <div class="title">Title1</div>
                    <div class="children">

                        <div>
                            <div class="tree">
                                <div class="title">Title2</div>
                                <div class="children"><div></div></div>
                            </div>
                            <div class="tree">
                                <div class="title">Title2</div>
                                <div class="children">

                                    <div>
                                        <div class="tree">
                                            <div class="title">Title2</div>
                                            <div class="children"><div></div></div>
                                        </div>
                                        <div class="tree">
                                            <div class="title">Title2</div>
                                            <div class="children"><div></div></div>
                                        </div>
                                        <div class="tree">
                                            <div class="title">Title2</div>
                                            <div class="children"><div></div></div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="tree">
                    <div class="title">Title1</div>
                    <div class="children">

                        <div>
                            <div class="tree">
                                <div class="title">Title2</div>
                                <div class="children"><div></div></div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/@shopify/draggable@1.0.0-beta.11/lib/draggable.bundle.js"></script>
<script type="module" src="/js/index.js"></script>